DEVICE_PATH := device/legion/halo

# A/B
AB_OTA_UPDATER := true
AB_OTA_PARTITIONS +=	\
	system		\
	vendor		\
	vendor_dlkm

# architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv9-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 := arm64-v9a

# bootloader
TARGET_BOOTLOADER_BOARD_NAME := taro
TARGET_NO_BOOTLOADER := true

#Display
TARGET_SCREEN_DENSITY := 480

# android kernel
BOARD_KERNEL_IMAGE_NAME := Image
TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilt/ksu/Image

# partition controll
BOARD_BOOTIMAGE_PARTITION_SIZE := 0x6000000
BOARD_RECOVERY_PARTITION_SIZE := 0x6400000
BOARD_SUPER_PARTITION_SIZE := 0x280000000

BOARD_SUPER_PARTITION_GROUPS := super
BOARD_SUPER_SIZE := 0x140000000
BOARD_SUPER_PARTITION_LIST +=		\
	system				\
	vendor				\
	vendor_dlkm

BOARD_USES_VENDOR_DLKMIMAGE := true
BOARD_VENDOR_DLKMIMAGE_FILE_SYSTEM_TYPE := ext4
TARGET_COPY_OUT_VENDOR_DLKM := vendor_dlkm
