DEVICE_PATH := device/legion/halo

#OTA assert
TARGET_OTA_ASSERT_DEVICE := halo
TARGET_SKIP_OTA_PACKAGE := false

# A/B
AB_OTA_UPDATER := true
AB_OTA_PARTITIONS +=	\
	boot		\
	recovery	\
	odm		\
	product		\
	system		\
	system_ext	\
	vendor		\
	vendor_dlkm	\
	vendor_boot	\
	vbmeta		\
	vbmeta_system

# recovery
PRODUCT_BUILD_RECOVERY_IMAGE := true
BUILDING_RECOVERY_IMAGE := true
TARGET_NO_RECOVERY := false
BOARD_USES_RECOVERY_AS_BOOT := false
BOARD_MOVE_RECOVERY_RESOURCES_TO_VENDOR_BOOT := false
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/prebuilt/etc/fstab.qcom
BOARD_EXCLUDE_KERNEL_FROM_RECOVERY_IMAGE := true

# vendor_boot
#BOARD_INCLUDE_RECOVERY_RAMDISK_IN_VENDOR_BOOT := true
BOARD_MOVE_GSI_AVB_KEYS_TO_VENDOR_BOOT := true

# architecture
TARGET_IS_64_BIT := true
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv9-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 := arm64-v9a
TARGET_CPU_VARIANT := generic
TARGET_CPU_VARIANT_RUNTIME := oryon


# bootloader
TARGET_BOOTLOADER_BOARD_NAME := taro
TARGET_NO_BOOTLOADER := true

#platform infomation
TARGET_BOARD_PLATFORM := taro
BOARD_USES_QCOM_HARDWARE := true
BOARD_USES_GENERIC_KERNEL_IMAGE := true

#Display
TARGET_SCREEN_DENSITY := 480

# android kernel
TARGET_NO_KERNEL := false
BOARD_BOOT_HEADER_VERSION := 4
STOCK_KERNEL_ZUI_VER := 14.0.697
KERNEL_VARIANT := ksu
BOARD_BOOTIMG_HEADER_VERSION := 4
TARGET_PREBUILT_DTB := $(DEVICE_PATH)/prebuilt/$(STOCK_KERNEL_ZUI_VER)/dtb
BOARD_MKBOOTIMG_ARGS += --header_version $(BOARD_BOOTIMG_HEADER_VERSION)
BOARD_KERNEL_CMDLINE := androidboot.selinux=permissive
BOARD_KERNEL_CMDLINE +=	\
	androidboot.boot_devices=soc/1d84000.ufshc
BOARD_KERNEL_PAGESIZE := 4096
BOARD_KERNEL_IMAGE_NAME := Image
TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilt/$(KERNEL_VARIANT)/Image
BOARD_PREBUILT_DTBOIMAGE := $(DEVICE_PATH)/prebuilt/$(STOCK_KERNEL_ZUI_VER)/dtbo.img
BOARD_RAMDISK_USE_XZ := true

# partition controll
BOARD_FLASH_BLOCK_SIZE := 0x4000
BOARD_BOOTIMAGE_PARTITION_SIZE := 0x6000000
BOARD_RECOVERY_PARTITION_SIZE := 0x6400000
BOARD_DTBOIMG_PARTITION_SIZE := 0x1800000
BOARD_VENDOR_BOOTIMAGE_PARTITION_SIZE := 0x6000000
BOARD_SUPER_PARTITION_SIZE := 10737418240
BOARD_VBMETA_PARTITION_SIZE := 0x10000
BOARD_VBMETA_SYSTEM_PARTITION_SIZE := 0x10000
BOARD_METADATA_PARTITION_SIZE := 0x1000000
BOARD_SUPER_PARTITION_GROUPS := knto_halo
BOARD_KNTO_HALO_SIZE := 5366611968
BOARD_KNTO_HALO_PARTITION_LIST +=	\
	odm				\
	product				\
	system				\
	system_ext			\
	vendor				\
	vendor_dlkm

BOARD_USES_VENDOR_DLKMIMAGE := true
BOARD_ODMIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_PRODUCTIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_SYSTEMIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_SYSTEM_EXTIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VENDOR_DLKMIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := ext4

# partition copy out
TARGET_COPY_OUT_VENDOR := vendor
TARGET_COPY_OUT_PRODUCT := product
TARGET_COPY_OUT_SYSTEM_EXT := system_ext
TARGET_COPY_OUT_ODM := odm
TARGET_COPY_OUT_VENDOR_DLKM := vendor_dlkm

#SEAndroid
TARGET_USES_PREBUILT_VENDOR_SEPOLICY := false
include device/qcom/sepolicy_vndr/SEPolicy.mk
SELINUX_IGNORE_NEVERALLOWS := false

##metadata partition
BOARD_USES_METADATA_PARTITION := true

#AVB
BOARD_AVB_ENABLE := true
BOARD_AVB_MAKE_VBMETA_IMAGE_ARGS += --flags 3
BOARD_AVB_RECOVERY_KEY_PATH := external/avb/test/data/testkey_rsa8192.pem
BOARD_AVB_RECOVERY_ALGORITHM := SHA256_RSA8192
BOARD_AVB_RECOVERY_ROLLBACK_INDEX := 1
BOARD_AVB_RECOVERY_ROLLBACK_INDEX_LOCATION := 1

# VINTF
DEVICE_MANIFEST_FILE += $(DEVICE_PATH)/manifest.xml

##disable configs
TARGET_USES_NQ_NFC := false
BOARD_HAVE_MTK_FM := false
