DEVICE_PATH := device/legion/halo

# A/B
AB_OTA_UPDATER := true
AB_OTA_PARTITIONS +=	\
	odm		\
	product		\
	system		\
	system_ext	\
	vendor		\
	vendor_dlkm

# architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv9-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 := arm64-v9a

# bootloader
TARGET_BOOTLOADER_BOARD_NAME := taro
TARGET_NO_BOOTLOADER := true

#Display
TARGET_SCREEN_DENSITY := 480

# android kernel
BOARD_BOOTIMG_HEADER_VERSION := 4
BOARD_MKBOOTIMG_ARGS += --header_version $(BOARD_BOOTIMG_HEADER_VERSION)
BOARD_KERNEL_CMDLINE := androidboot.selinux=permissive
BOARD_KERNEL_PAGESIZE := 4096
BOARD_KERNEL_IMAGE_NAME := Image
TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilt/ksu/Image

# partition controll
BOARD_FLASH_BLOCK_SIZE := 0x4000
BOARD_BOOTIMAGE_PARTITION_SIZE := 0x6000000
BOARD_RECOVERY_PARTITION_SIZE := 0x6400000
BOARD_SUPER_PARTITION_SIZE := 0x280000000

BOARD_SUPER_PARTITION_GROUPS := knto_halo
BOARD_KNTO_HALO_SIZE := 0x140000000
BOARD_KNTO_HALO_PARTITION_LIST +=	\
	odm				\
	product				\
	system				\
	system_ext			\
	vendor				\
	vendor_dlkm

BOARD_USES_VENDOR_DLKMIMAGE := true
BOARD_VENDOR_DLKMIMAGE_FILE_SYSTEM_TYPE := ext4
TARGET_COPY_OUT_VENDOR_DLKM := vendor_dlkm

#AVB
BOARD_AVB_ENABLE := true
BOARD_AVB_MAKE_VBMETA_IMAGE_ARGS += --flags 3
BOARD_AVB_RECOVERY_KEY_PATH := external/avb/test/data/testkey_rsa8192.pem
BOARD_AVB_RECOVERY_ALGORITHM := SHA256_RSA8192
BOARD_AVB_RECOVERY_ROLLBACK_INDEX := 1
BOARD_AVB_RECOVERY_ROLLBACK_INDEX_LOCATION := 1
